spring:
  application:
    name: suspicious-car

  datasource:
    url: jdbc:mysql://localhost:3306/suspicious_car_db
    username: root
    password: root

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
